### ISSUE TITLE
Recommendation: Remove containers you don't need

### ISSUE THREAD

**Issue by melissamcewen** [Robinnnnnn/prj-rev-bwfs-dasmoto#3]
https://github.com/Robinnnnnn/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L8
Elements that are just used to contain things for targeting with CSS are known as "containers" . Good job using this technique. But it can make things complicated sometimes so I try to avoid using it whenever possible. With this you can remove the ` <div id="header">` and target the h2 for the background:

```css
h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

```
